# Generated by Django 5.2.4 on 2025-07-14 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('voucher_type', models.CharField(choices=[('BPV', 'Bank Payment'), ('BRV', 'Bank Receipt'), ('CPV', 'Cash Payment'), ('CRV', 'Cash Receipt')], max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payee', models.CharField(max_length=255)),
                ('memo', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BankPaymentVoucher',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vouchers.voucher')),
                ('bank', models.CharField(max_length=100)),
                ('cheque_no', models.CharField(max_length=50)),
            ],
            bases=('vouchers.voucher',),
        ),
        migrations.CreateModel(
            name='BankReceiptVoucher',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vouchers.voucher')),
                ('bank', models.CharField(max_length=100)),
                ('inst_type', models.CharField(max_length=50, verbose_name='Instrument Type')),
                ('inst_no', models.CharField(max_length=50, verbose_name='Instrument Number')),
            ],
            bases=('vouchers.voucher',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vouchers.voucher')),
            ],
        ),
    ]
